### PR TITLE
Address "v" prefixing in the FAQ

### PR DESCRIPTION
**Pull request by beck**
As suggested here: https://github.com/mojombo/semver/issues/204#issuecomment-47609174

### CODE REVIEW

**Comment by beck** [comment]
:bell:

**Comment by PowerKiKi** [comment]
I would rather discourage the used of "v" prefix. The suggested text, while it clarify some aspects, leave the decision up to the reader. I would rather add a sentence to the effect of:

    SemVer discourage the use of any prefix for the sake of clarity and ease of interoperability.

**Comment by beck** [comment]
Usually a good quality for interoperability (aka compatibility) is great.  What's even better is backward-compatiblity.

From semver 1.0:

> When tagging releases in a version control system, the tag for a version MUST be "vX.Y.Z" e.g. "v3.1.0".

I'm not sure why this was removed. This pull would not be needed if Version 2 addressed the issue with a "MAY" or "MUST NOT".

**Comment by FichteFoll** [comment]
The current spec only specifies the version itself, not how you use or embed it. Imo it's better to make usage of semver as permissive as possible while also being strict on the actual semver part. Thus, only mentioning the `v` prefix in the FAQ and not in the spec itself makes more sense than more or less arbitrarily have a special case, because there are no special cases.

**Comment by julmot** [comment]
:+1: a clearification is necessary regardless if it will be in the spec of FAQ.

**Comment by beck** [comment]
@mojombo What's up with this repo? Is it dead?

**Comment by Haacked** [comment]
Looks good to me.

**Pull request merged**
